import Link from "next/link";

const grades = [
  ["S", "9.0–10.0", "Exceptional: comfortably exceeds the strongest practical benchmark."],
  ["A", "8.0–8.9", "Very strong: reliable for the stated content with room for build-specific caveats."],
  ["B", "7.0–7.9", "Strong: normally comfortable, but some layers or conditions need attention."],
  ["C", "6.0–6.9", "Functional: can work, but the build has clear content or reliability limits."],
  ["D", "5.0–5.9", "Needs improvement: playable with care and likely to feel inconsistent."],
  ["E", "3.0–4.9", "Fragile: major gaps are likely to show up before demanding content."],
  ["F", "1.0–2.9", "Critical gaps: the imported evidence does not support dependable performance."],
] as const;

export default function AboutPage() {
  return <main className="about-page">
    <header className="about-header"><Link href="/" className="about-back">← Back to analyzer</Link><p className="eyebrow">PoB Rating Checker</p><h1>How the grading system works</h1><p>Ratings are a transparent screening tool for Path of Building exports. They describe the evidence in the imported setup; they are not a promise that every map, boss, or gameplay decision will behave the same way.</p></header>
    <section className="about-flow" aria-label="How a build becomes a rating">
      <div className="about-flow-step"><span>01</span><strong>Read the PoB snapshot</strong><small>Skills, support gems, items, conditions, DPS, maximum hit, recovery, and resistances.</small></div>
      <i aria-hidden="true">→</i>
      <div className="about-flow-step"><span>02</span><strong>Choose the real damage basis</strong><small>Meaningful Hit DPS or DoT DPS is selected; the largest configured number is not blindly trusted.</small></div>
      <i aria-hidden="true">→</i>
      <div className="about-flow-step"><span>03</span><strong>Grade the build</strong><small>Offence, defence, mapping, bossing, and content breadth become scores from 1.0 to 10.0.</small></div>
      <i aria-hidden="true">→</i>
      <div className="about-flow-step about-flow-final"><span>04</span><strong>Apply the weakest link</strong><small>Overall is restrained when damage, survivability, or endgame coverage is missing.</small></div>
    </section>
    <section className="about-grid">
      <article><h2>Power, survival, and coverage</h2><p><strong>Offence</strong> measures the strongest meaningful damage channel in the export. If DoT DPS is materially higher than Hit DPS, DoT becomes the offence basis. If Hit DPS is higher—or DoT is only a small trace—the rating follows Hit DPS. If neither is available, an aggregate PoB value is used as a fallback.</p><p><strong>Defence</strong> combines maximum-hit evidence, resistances, effective hit pool, mitigation, avoidance, recovery, endurance layers, and physical damage conversion. Maximum hit is the anchor because a large pool alone does not mean the character survives a real spike.</p><p><strong>Content coverage</strong> rates T16 mapping, pinnacle bosses, invitations, delve, Blight/waves, and Ritual/arena waves separately. A build can be excellent at one job and only conditional at another.</p><p><strong>Overall</strong> uses a weakest-link adjustment across all three: high offence cannot completely hide missing defence or narrow endgame coverage.</p></article>
      <article><h2>What the number means</h2><p>The score is on a 1.0–10.0 scale. The letter grade is simply the named band for that score, so rating and grade are two views of the same result.</p><div className="about-thresholds"><div><b>1.0</b><span>Not ready for dependable white maps</span></div><div><b>3.0</b><span>Yellow-map capable with care</span></div><div><b>5.0</b><span>Comfortable T16 baseline</span></div><div><b>7.0</b><span>Strong endgame foundation</span></div><div><b>8.0</b><span>Very strong and reliable</span></div><div><b>9.0+</b><span>Exceptional practical evidence</span></div></div><p className="about-note">These are practical benchmarks, not guarantees. Map mods, altars, mechanics, uptime, player movement, and boss phases can still change the result.</p></article>
    </section>
    <section className="about-section"><h2>Grades</h2><div className="grade-table">{grades.map(([grade, range, detail]) => <div key={grade}><strong>{grade}</strong><b>{range}</b><span>{detail}</span></div>)}</div></section>
    <section className="about-section"><h2>Why configured PoB matters</h2><p>PoB exports preserve the skills, equipment, passives, configuration, and conditional effects you selected. That is why a correctly configured personal export is the preferred source. PoE Ninja builds are useful reference material, but they may omit the original settings or represent a different moment of the character.</p><p>When the isolated calculation worker is available, the analyzer can compare baseline, typical, burst, sustained, and peak states. Those comparisons explain how much of the displayed ceiling survives once temporary conditions and delivery limits are made explicit.</p></section>
    <section className="about-section about-faq" id="faq-main-skill"><h2>FAQ: why is Offence ? or 0?</h2><details open><summary>Why does the site warn me when I have multiple six-links?</summary><p>Multiple six-links can be perfectly valid, but a six-link by itself does not prove that the setup is the skill you actually use. One may be an aura package, movement setup, utility skill, alternate bossing skill, or a different calculation state. The warning is a failsafe against rating the wrong skill.</p></details><details><summary>How do I configure the correct main skill?</summary><p>In Path of Building, select the active skill you actually cast or use for damage. Make sure it is the intended main calculation and that <strong>Include in Full DPS</strong> is checked for that setup. Do not leave an aura, utility skill, movement skill, or alternate six-link selected as the Full DPS source. Export a fresh PoB snapshot after changing it.</p></details><details><summary>Why can Offence still show ? after the skill name looks correct?</summary><p>The skill name and the DPS value are separate pieces of evidence. If PoB did not export a positive Full DPS, Hit DPS, or DoT DPS value for the selected state, the site cannot invent one safely. Check the skill’s calculation tab, active skill part, skill count, conditions, and Full DPS checkbox in PoB, then export again.</p></details><details><summary>Does a ? mean the build has no damage?</summary><p>No. It means the imported snapshot does not contain enough reliable, correctly selected DPS evidence for a defensible rating. The site prefers a visible warning over silently rating a different six-link or guessing a combat state.</p></details></section>
    <section className="about-section"><h2>What “evidence” means</h2><p>Evidence means the analyzer found a relevant value or effect in the imported build—such as a PoB DPS channel, maximum-hit value, resistance, support gem, unique-item modifier, or configured condition. It does not mean the effect is always active. Temporary, ramping, conditional, or unverified effects become review flags and are not treated as permanent power.</p><p>“Mapping” is the old “Clear” category: it estimates normal-pack coverage, area damage, secondary effects, movement, and on-kill support. “Bossing” focuses on single-target delivery, uptime, ramping, and whether the build can maintain its damage against a boss. Content coverage then combines those signals with survival and delivery-specific limits so the report can say where the build is viable instead of hiding everything behind one number.</p></section>
    <section className="about-section"><h2>Data sources and limits</h2><p>The site reads the PoB export first, then enriches supported gem and unique-item metadata from local Path of Building registries. External data can improve names, icons, and context; it does not override the imported build's configured combat values. The report calls out unavailable or unverified data instead of silently inventing it.</p></section>
    <Link href="/" className="about-cta">Analyze a build →</Link>
  </main>;
}
