"use client";
import { useState } from "react";

type Evidence = { kind: string; label: string; detail: string };
type Condition = { id: string; displayName: string; category: string; reliability: string; confidence: string; explanation: string; sourceDetected: boolean; activationRequirement: string; statsAffected: string[]; evidence: Evidence[] };
type Asset = { category: string; name: string; detail: string; iconUrl?: string; attributeColor: string };
type Metric = { value: number | null; status: string; confidence: string };
type Report = {
  build: { identity: { name: string; level?: number; className?: string; ascendancy?: string; version?: string }; skills: string[]; items: string[]; sections: string[]; rawXml: string; sources: { category: string; name: string; detail: string }[]; sourceAssets: Asset[]; importedStats: Record<string, number | string | undefined>; passiveNodes: { name: string; type: string; allocated: boolean }[] };
  conditions: Condition[]; confidence: string; audit: { persistent: number; conditional: number; unverified: number; status: string }; honesty: { score: number; label: string; explanation: string; factors: { label: string; points: number; explanation: string }[] }; topNotables: { name: string; type: string; allocated: boolean }[]; sourceSummary: { gems: number; items: number; flasks: number; passives: number; ascendancies: number }; recommendations: { title: string; detail: string; conditionId: string }[]; warnings: string[]; assumptions: string[];
};

const example = "https://pobb.in/0oChNQNO2-dg";
const formatNumber = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value.toLocaleString() : "Unavailable";

export function Analyzer() {
  const [url, setUrl] = useState(() => typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("build") ?? "" : "");
  const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  async function analyze() {
    setLoading(true); setError(""); setReport(null);
    try { const res = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); window.history.replaceState({}, "", `/?build=${encodeURIComponent(url)}`); setReport(body); }
    catch (e) { setError(e instanceof Error ? e.message : "Analysis failed."); }
    finally { setLoading(false); }
  }
  return <>{!report ? <section className="hero"><p className="eyebrow">A second opinion for your PoB numbers</p><h2>Make the <span>conditions</span> visible.</h2><p>Import a Path of Building link and see which parts of the displayed build are sourced, temporary, situational, ramp-dependent—or still unknown.</p><div className="input-row"><label className="sr-only" htmlFor="pob-url">pobb.in URL</label><input id="pob-url" className="url-input" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://pobb.in/..." onKeyDown={e => { if (e.key === "Enter") void analyze(); }} /><button className="button" onClick={() => void analyze()} disabled={loading || !url.trim()}>{loading ? "Reading build…" : "Analyze build"}</button></div><button className="example" onClick={() => setUrl(example)}>Try the example build →</button>{error && <div className="error" role="alert">{error}</div>}<p className="privacy">Only supported pobb.in links are fetched. Results are analysis estimates, not gameplay guarantees.</p></section> : <ReportView report={report} onReset={() => { setReport(null); window.history.replaceState({}, "", "/"); }} />}</>;
}

function ReportView({ report, onReset }: { report: Report; onReset: () => void }) {
  const identity = report.build.identity;
  const offence = report.conditions.filter(c => c.category === "offence" || c.category === "both");
  const defence = report.conditions.filter(c => c.category === "defence" || c.category === "both");
  const stats = report.build.importedStats;
  return <section className="report">
    <div className="report-head"><div><p className="eyebrow">Honesty build checker</p><h2>{identity.name}</h2><p className="muted">{[identity.className, identity.ascendancy, identity.level && `Level ${identity.level}`, identity.version && `PoB ${identity.version}`].filter(Boolean).join(" · ") || "Identity fields available in export"}</p></div><div className="honesty-score"><span>HONESTY</span><strong>{report.honesty.score}<small>/10</small></strong><em>{report.honesty.label}</em></div></div>
    <div className="grid"><div className="card"><h3>Honesty rating</h3><div className="value">{report.honesty.score}/10</div><div className="metric-note">{report.honesty.explanation}</div></div><div className="card"><h3>Visible conditionals</h3><div className="value">{report.conditions.length}</div><div className="metric-note">{report.audit.persistent} persistent · {report.audit.conditional} conditional · {report.audit.unverified} unverified kept in audit</div></div><div className="card"><h3>Calculation status</h3><div className="value">{stats.source === "pob-calcs" ? "Imported" : "Worker required"}</div><div className="metric-note">PoB computes final DPS and defence values through its calculation engine, not from the pobb.in export alone.</div></div></div>
    <CombatSnapshot stats={stats} />
    <TreePreview report={report} />
    <SourceInventory assets={report.build.sourceAssets} summary={report.sourceSummary} />
    <div className="section card"><div className="external-header"><div><h3>Poe.ninja comparison</h3><p className="muted">Poe.ninja can be useful as a population reference, but its displayed DPS is not a substitute for this build’s controlled PoB scenarios.</p></div><a className="text-link" href="https://poe.ninja/poe1/builds" target="_blank" rel="noreferrer">Open Poe.ninja ↗</a></div><div className="unavailable-panel"><strong>Character snapshot not automatically matched</strong><span>A pobb.in link does not contain a Poe.ninja account/character identity. Add an explicit profile reference in a later comparison flow; do not guess a match.</span></div></div>
    <ScenarioPanel xml={report.build.rawXml} />
    <div className="section columns"><ConditionGroup title="Offensive conditions" items={offence} /><ConditionGroup title="Defensive conditions" items={defence} /></div>
    <div className="section columns"><div className="card"><h3>Recommendations</h3>{report.recommendations.length ? <ul className="list">{report.recommendations.map(r => <li key={r.conditionId}><strong>{r.title}:</strong> {r.detail}</li>)}</ul> : <p className="muted">No evidence-backed findings yet.</p>}</div><div className="card"><h3>Why this rating</h3>{report.honesty.factors.length ? <ul className="list">{report.honesty.factors.map(f => <li key={f.label}><strong>{f.points}:</strong> {f.label}</li>)}</ul> : <p className="muted">No score deductions were found in the imported condition set.</p>}</div></div>
    <div className="section columns"><div className="card"><h3>Warnings</h3><ul className="list">{report.warnings.map(x => <li key={x}>{x}</li>)}</ul></div><div className="card"><h3>Assumptions</h3><ul className="list">{report.assumptions.map(x => <li key={x}>{x}</li>)}</ul></div></div>
    <details className="diagnostics"><summary>Show raw diagnostic details</summary><pre>{report.build.rawXml.slice(0, 12000)}</pre></details><button className="example" onClick={onReset}>← Analyze another build</button>
  </section>;
}

function CombatSnapshot({ stats }: { stats: Record<string, number | string | undefined> }) {
  const values: [string, string, unknown][] = [["Full PoB DPS", "fullDps", stats.fullDps], ["Configured skill DPS", "totalDps", stats.totalDps], ["Average hit", "averageHit", stats.averageHit], ["Life", "life", stats.life], ["Effective hit pool", "effectiveHealthPool", stats.effectiveHealthPool], ["Spell suppression", "spellSuppression", stats.spellSuppression]];
  return <div className="section card"><div className="external-header"><div><h3>Imported PoB stats</h3><p className="muted">Exact values are shown only when present in imported calculation data or returned by the Headless PoB worker.</p></div><span className={`source-badge ${stats.source === "pob-calcs" ? "source-live" : "source-offline"}`}>{stats.source === "pob-calcs" ? "POB CALCS" : "NOT IN EXPORT"}</span></div><div className="stat-grid">{values.map(([label, key, value]) => <div className="stat-tile" key={key}><span>{label}</span><strong>{formatNumber(value)}{typeof value === "number" && /suppression/i.test(label) ? "%" : ""}</strong><small>{typeof value === "number" ? "Imported value" : "Unavailable without calculation engine"}</small></div>)}</div><div className="scenario-note">Scenario outputs will become authoritative after the isolated PoB worker is available: Peak → Realistic burst → Initial boss → Sustained boss → Mapping.</div></div>;
}

function TreePreview({ report }: { report: Report }) { return <div className="section card"><div className="external-header"><div><h3>Passive tree preview</h3><p className="muted">Allocated names are imported from the PoB tree data. Node contribution percentages require controlled engine comparisons.</p></div><span className="source-badge source-live">{report.build.passiveNodes.length} NODES</span></div><div className="tree-layout"><div className="tree-map">{report.build.passiveNodes.slice(0, 18).map((node, index) => <div key={`${node.name}-${index}`} className={`tree-node tree-node-${index % 6} ${node.type}`} title={`${node.name} · ${node.type}`}><span>{node.name.slice(0, 2).toUpperCase()}</span></div>)}</div><div className="notable-list">{report.topNotables.length ? report.topNotables.map(node => <div key={node.name}><span className={`node-dot ${node.type}`}></span><strong>{node.name}</strong><small>{node.type} · contribution unavailable until engine comparison</small></div>) : <p className="muted">No named nodes were found in the imported tree section.</p>}</div></div></div>; }

function SourceInventory({ assets, summary }: { assets: Asset[]; summary: Report["sourceSummary"] }) { return <div className="section card"><div className="external-header"><div><h3>Source inventory</h3><p className="muted">Every visible source is tied to imported gem, item, flask, or tree evidence.</p></div><div className="source-pills"><span>Gems {summary.gems}</span><span>Items {summary.items}</span><span>Flasks {summary.flasks}</span><span>Tree {summary.passives + summary.ascendancies}</span></div></div><div className="asset-grid">{assets.filter(asset => asset.category !== "passive" || asset.name).slice(0, 24).map((asset, index) => <div className="asset-card" key={`${asset.category}-${asset.name}-${index}`}><div className={`asset-icon asset-${asset.attributeColor}`}>{asset.iconUrl ? <img src={asset.iconUrl} alt="" /> : <span>{asset.category === "gem" ? "◆" : asset.category === "flask" ? "◈" : "✦"}</span>}</div><div><strong className={`asset-name asset-text-${asset.attributeColor}`}>{asset.name}</strong><small>{asset.category} · {asset.detail}</small></div></div>)}</div></div>; }

function ConditionGroup({ title, items }: { title: string; items: Condition[] }) { return <div className="card"><h3>{title}</h3>{items.length ? items.map(c => <details className="condition" key={c.id}><summary><span><span className="condition-name">{c.displayName}</span><span className="condition-sub">{c.sourceDetected ? "Source evidence found" : "Source unverified"}</span></span><span className={`tag ${c.sourceDetected ? "tag-good" : "tag-unknown"}`}>{c.reliability} · {c.confidence}</span></summary><p>{c.explanation}</p><p className="requirement"><strong>Requires:</strong> {c.activationRequirement}</p><p className="requirement"><strong>Affects:</strong> {c.statsAffected.join(", ")}</p><div className="evidence-list">{c.evidence.map((e, index) => <div className="evidence" key={`${e.label}-${index}`}><span>{e.kind}</span><div><strong>{e.label}</strong><small>{e.detail}</small></div></div>)}</div></details>) : <p className="muted">No configured conditions detected in this category.</p>}</div>; }

function ScenarioPanel({ xml }: { xml: string }) { const [loading, setLoading] = useState(false); const [result, setResult] = useState<Record<string, Metric> | null>(null); const [error, setError] = useState(""); const [encounterSeconds, setEncounterSeconds] = useState(30); async function run() { setLoading(true); setError(""); try { const response = await fetch("/api/scenarios", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ xml, encounterSeconds }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setResult(body); } catch (e) { setError(e instanceof Error ? e.message : "Scenario calculation unavailable."); } finally { setLoading(false); } } const labels = ["configured", "peak", "burst", "initial", "sustained", "mapping"]; return <div className="section card"><div className="scenario-header"><div><h3>Combat scenarios</h3><p className="muted">No scenario value is estimated. Results appear only when the authoritative PoB worker returns them.</p></div><div className="scenario-actions"><label>Encounter seconds<input className="duration-input" type="number" min="1" max="300" value={encounterSeconds} onChange={e => setEncounterSeconds(Number(e.target.value) || 30)} /></label><button className="button scenario-button" onClick={() => void run()} disabled={loading}>{loading ? "Calculating…" : "Run scenarios"}</button></div></div>{error && <p className="engine-status">{error}</p>}{result && <div className="scenario-grid">{labels.map(id => { const metric = result[id]; return <div className="scenario-metric" key={id}><span>{id}</span><strong>{metric?.value === null || metric?.value === undefined ? "Unavailable" : `${Math.round(metric.value).toLocaleString()} DPS`}</strong><small>{metric?.status} · {metric?.confidence} confidence</small></div>; })}</div>}</div>; }
