import type { Condition, ConditionEvidence, NormalizedBuild, Reliability, Confidence } from "@/src/types/domain";

type Rule = {
  id: string; displayName: string; category: "offence" | "defence" | "both"; field?: RegExp; source: RegExp;
  reliability: Reliability; confidence: Confidence; requirement: string; explanation: string; stats: string[]; sourceOnly?: boolean;
};

const rules: Rule[] = [
  { id: "power-charges", displayName: "Power Charges", category: "offence", field: /powercharges|power charges/i, source: /conviction of power|minimum power charge|power charge/i, reliability: "Reliable", confidence: "High", requirement: "Conviction of Power supplies the configured minimum charges.", explanation: "Conviction of Power is present in the imported build and supplies minimum Power Charges. This is a persistent source, not a temporary combat condition.", stats: ["critical strike chance", "damage"] },
  { id: "frenzy-charges", displayName: "Frenzy Charges", category: "offence", field: /frenzycharges|frenzy charges/i, source: /frenzy charge|frenzycharge|blood rage|frenzy generation/i, reliability: "Conditional", confidence: "Medium", requirement: "A Frenzy Charge generator must exist and be usable in the encounter.", explanation: "Frenzy Charges are configured, but no generator was found in the imported skills, items, ascendancy, or passive evidence. Treat this as unavailable for the current audit, while retaining uncertainty if source detection is incomplete.", stats: ["attack/cast speed", "damage"] },
  { id: "endurance-charges", displayName: "Endurance Charges", category: "defence", field: /endurancecharges|endurance charges/i, source: /conviction of power|minimum endurance charge|endurance charge|enduring cry/i, reliability: "Reliable", confidence: "High", requirement: "Conviction of Power supplies the configured minimum charges.", explanation: "Conviction of Power is present in the imported build and supplies minimum Endurance Charges. This is a persistent defensive baseline, not an unverified temporary buff.", stats: ["physical damage reduction", "elemental resistance"] },
  { id: "flasks", displayName: "Active flasks", category: "offence", field: /flask/i, source: /flask|taste of hate|diamond flask|quicksilver/i, reliability: "Temporary", confidence: "Medium", requirement: "Flask charges and activation must be available.", explanation: "At least one flask condition or flask modifier is present. Charge sustain and boss uptime are not simulated in Phase 2.", stats: ["damage", "defence", "movement"] },
  { id: "arcane-surge", displayName: "Arcane Surge", category: "offence", field: /arcanesurge|arcane surge/i, source: /arcane surge/i, reliability: "Temporary", confidence: "High", requirement: "Arcane Surge must be granted and remain active.", explanation: "The imported skill setup contains Arcane Surge evidence. Its uptime depends on the linked skill and mana-spending cadence.", stats: ["spell damage", "cast speed"] },
  { id: "onslaught", displayName: "Onslaught", category: "offence", field: /onslaught/i, source: /onslaught|silver flask/i, reliability: "Temporary", confidence: "Medium", requirement: "Onslaught must be granted by a skill, item, or flask.", explanation: "Onslaught is a real source-backed buff when detected, but its uptime depends on the grant and encounter.", stats: ["attack/cast speed", "movement"] },
  { id: "sigil-of-power", displayName: "Sigil of Power", category: "both", field: /sigilofpower|sigil of power|sigil/i, source: /sigil of power/i, reliability: "Temporary", confidence: "High", requirement: "The character must remain inside Sigil of Power while its stages are built.", explanation: "Sigil of Power is source-backed, but peak benefits require time spent in the area and may be lost when the boss moves.", stats: ["damage", "damage reduction"] },
  { id: "frost-shield", displayName: "Frost Shield", category: "both", field: /frostshield|frost shield/i, source: /frost shield/i, reliability: "Temporary", confidence: "High", requirement: "Frost Shield must be active and the character must benefit from its area or stages.", explanation: "Frost Shield is a real imported skill source. Its defensive and offensive value is temporary and positioning-dependent.", stats: ["damage", "damage taken"] },
  { id: "arcane-cloak", displayName: "Arcane Cloak", category: "both", field: /arcan[e]?cloak|mana spent recently/i, source: /arcane cloak/i, reliability: "Temporary", confidence: "High", requirement: "Arcane Cloak must be active with sufficient available mana.", explanation: "Arcane Cloak can affect both offence and defence. The peak state is temporary and depends on mana availability and activation timing.", stats: ["damage", "guard", "damage taken"] },
  { id: "focus", displayName: "Focus", category: "both", field: /focus/i, source: /focus/i, reliability: "Temporary", confidence: "Medium", requirement: "Focus must be activated and its cooldown must be available.", explanation: "Focus is source-backed when detected, but it is a cooldown-limited combat state.", stats: ["damage", "defence"] },
  { id: "enemy-low-life", displayName: "Enemy is low life", category: "offence", field: /lowlife|low life/i, source: /punishment|low life|culling strike/i, reliability: "Situational", confidence: "High", requirement: "The enemy must be in its low-life phase.", explanation: "Punishment provides a valid source for this configured target state, but the benefit is phase-dependent and should not be treated as permanent boss DPS.", stats: ["damage"] },
  { id: "enemy-full-life", displayName: "Enemy is full life", category: "offence", field: /fulllife|full life/i, source: /full life|onslaught|first hit/i, reliability: "Situational", confidence: "High", requirement: "The enemy must be at full life.", explanation: "This target-state assumption is strongest on the first hit or at the start of a fresh encounter.", stats: ["damage"] },
  { id: "recently-killed", displayName: "Recently killed", category: "offence", field: /recentlykilled|recently killed/i, source: /recently killed|on kill|headhunter|mapping/i, reliability: "Mapping-only", confidence: "High", requirement: "A qualifying enemy must have died recently.", explanation: "Recently-killed effects are not automatically boss-appropriate. They may work during add phases, but not against a continuously isolated pinnacle boss.", stats: ["damage", "speed"] },
  { id: "recently-hit", displayName: "Recently hit", category: "defence", field: /recentlyhit|recently hit/i, source: /recently hit|hit recently|when hit/i, reliability: "Conditional", confidence: "Medium", requirement: "The character must have been hit within the relevant window.", explanation: "This effect can be active during combat but is not guaranteed before the first hit or during downtime.", stats: ["defence", "recovery"] },
  { id: "recently-attacked-block", displayName: "Attack block after attacking recently", category: "defence", source: /forbidden flame|forbidden flesh|attacked recently|chance to block attack/i, reliability: "Conditional", confidence: "High", requirement: "The character must have attacked recently.", explanation: "The Forbidden Flame/Flesh source makes this a real conditional defense. It should be active only after the attack trigger window is satisfied.", stats: ["attack block"] , sourceOnly: true },
  { id: "recently-cast-block", displayName: "Spell block after casting recently", category: "defence", source: /forbidden flame|forbidden flesh|cast a spell recently|chance to block spell/i, reliability: "Conditional", confidence: "High", requirement: "The character must have cast a spell recently.", explanation: "The Forbidden Flame/Flesh source makes this a real conditional defense. It should be active only after the spell-cast trigger window is satisfied.", stats: ["spell block"], sourceOnly: true },
  { id: "stationary", displayName: "Stationary condition", category: "offence", field: /stationary|while stationary/i, source: /stationary|while stationary|immobile/i, reliability: "Situational", confidence: "Medium", requirement: "The character must remain stationary.", explanation: "The condition can be valid without being practical for every encounter or mechanic.", stats: ["damage", "defence"] },
  { id: "nearby-enemy", displayName: "Nearby enemy", category: "offence", field: /nearbyenemy|nearby enemy/i, source: /nearby enemy|close range|within/i, reliability: "Situational", confidence: "Medium", requirement: "The enemy must remain within the relevant distance.", explanation: "Range and movement determine whether this condition overlaps with other configured effects.", stats: ["damage", "defence"] },
];

function evidenceFor(rule: Rule, build: NormalizedBuild): ConditionEvidence[] {
  const evidence: ConditionEvidence[] = [];
  for (const field of build.configFields) if (rule.field?.test(`${field.name} ${field.value}`)) evidence.push({ kind: "configuration", label: field.name, detail: `Configured value: ${field.value || "present"}` });
  const source = build.sources.find((entry) => entry.category !== "configuration" && rule.source.test(`${entry.name} ${entry.detail}`));
  if (source) evidence.push({ kind: source.category === "gem" ? "skill" : source.category === "item" || source.category === "flask" ? "item" : source.category, label: source.name, detail: source.detail });
  return evidence;
}

export function detectConditions(build: NormalizedBuild): Condition[] {
  return rules.flatMap((rule) => {
    const evidence = evidenceFor(rule, build);
    const configured = evidence.some((item) => item.kind === "configuration");
    const sourceDetected = evidence.some((item) => item.kind !== "configuration");
    if (!configured && !(rule.sourceOnly && sourceDetected)) return [];
    const knownEncounterCondition = rule.id === "recently-killed" && configured && !sourceDetected;
    const reliable = sourceDetected && rule.reliability === "Reliable";
    return [{ id: rule.id, displayName: rule.displayName, category: rule.category, configured, sourceDetected, source: sourceDetected ? "Imported build evidence" : undefined, activationRequirement: rule.requirement, reliability: sourceDetected || knownEncounterCondition ? rule.reliability : "Unverified", confidence: sourceDetected || knownEncounterCondition ? rule.confidence : "Low", availability: reliable ? "available" : sourceDetected || knownEncounterCondition ? "conditional" : rule.id === "frenzy-charges" ? "unavailable" : "unverified", explanation: sourceDetected || knownEncounterCondition ? rule.explanation : `${rule.explanation} No matching source was found, so this remains unverified rather than being called invalid.`, pobField: evidence.find((item) => item.kind === "configuration")?.label, statsAffected: rule.stats, evidence }];
  });
}
